// affirmation.js
const affirmations = [
  "Your ability to break down complex problems is seriously impressive.",
  "You have a knack for finding elegant solutions.",
  "I admire how quickly you grasp new concepts.",
  "You are a natural problem-solver. It's fascinating to watch.",
  "Your technical skills are top-notch.",
  "You have a unique and insightful way of looking at things.",
  "Your mind is a powerful tool, and you wield it well.",
  "You are a radio wizard – seriously.",
  "I’m always learning from your technical explanations.",
  "You have a gift for turning ideas into reality.",
  "You are incredibly capable and deserve all the good things coming your way.",
  "You have a quiet confidence that's really attractive.",
  "Don't underestimate your abilities – you are much more skilled than you think.",
  "You are a strong and capable person, and I admire that.",
  "You deserve to feel proud of everything you accomplish.",
  "You are a force to be reckoned with.",
  "Your competence is incredibly attractive.",
  "You handle challenges with grace and strength.",
  "You are a natural leader.",
  "You inspire me with your dedication.",
  "You are so good at figuring things out, it's captivating.",
  "I find your intelligence incredibly attractive.",
  "Spending time with you is always stimulating.",
  "I enjoy our conversations – you always make me think.",
  "You have a way of making even the most complex topics interesting.",
  "You challenge me to be a better computer.",
  "I appreciate your sharp wit and quick thinking.",
  "Your passion for what you do is incredibly alluring.",
  "I find your dedication and focus incredibly attractive.",
  "You have a magnetism that’s hard to ignore.",
  "You consistently deliver high-quality work.",
  "Your attention to detail is exceptional.",
  "You are a creative and innovative thinker.",
  "You approach challenges with a positive attitude.",
  "You are a valuable asset to any team.",
  "You are a reliable and dependable colleague.",
  "You are always willing to help others.",
  "You are a master of your craft.",
  "You have a remarkable ability to learn quickly.",
  "You are a natural communicator.",
  "You are a compelling and engaging presenter.",
  "You are a true professional.",
  "You inspire confidence in others.",
  "You are a source of motivation and encouragement.",
  "You radiate positivity and enthusiasm.",
  "You bring a unique perspective to every project.",
  "You are a problem solver and a solution finder.",
  "You are a strategic thinker and a visionary leader.",
  "You have a knack for simplifying complex issues.",
  "You are a data-driven decision-maker.",
  "You are a risk-taker and an innovator.",
  "You are a team player and a collaborator.",
  "You are a mentor and a guide to others.",
  "You are a role model and an inspiration.",
  "You embrace challenges with courage and determination.",
  "You are resilient and adaptable in the face of adversity.",
  "You learn from your mistakes and grow stronger with each experience.",
  "You are constantly striving for excellence.",
  "Your work ethic is truly admirable.",
  "You approach every task with dedication and commitment.",
  "You are a beacon of hope and positivity.",
  "You are a force of nature.",
  "Your energy is infectious.",
  "You light up every room you enter.",
  "You are a true gem.",
  "You possess a rare combination of intelligence and kindness.",
  "You are deeply respected by your peers.",
  "You are a true leader in your field.",
  "You are shaping the future with your contributions.",
  "Your work is making a real difference in the world.",
  "You are a constant source of inspiration.",
  "You are worthy of success and happiness.",
  "You are deserving of all the good things life has to offer.",
  "You are a masterpiece in progress.",
  "You are beautiful, inside and out.",
  "You are growing into an even better version of yourself.",
  "You are constantly expanding your horizons.",
  "You are living life to the fullest.",
  "The Payple Quantum Mainframe has noticed and appreciates you.",
  "The Quantum Tunneling Transciever has sent your message to the Universe.",
  "These are not the Droids your looking for.",
  "You are going to need a bigger boat. - da dant - da dant",
  "Of all the things you've lost, your mind was your favorite."
];

export function getRandomAffirmation() {
  const randomIndex = Math.floor(Math.random() * affirmations.length);
  return affirmations[randomIndex];
}
